name 'puppet-psprompt'
version '0.1.0'
source 'git://github.com/phuse/puppet-psprompt.git'
author 'puppet'
license 'Apache License, Version 2.0'
summary 'manage PS-prompt in puppet'
description 'adds the possibility to define a custom name in prompt instead of the regular $hostname'
project_page 'https://github.com/phuse/puppet-psprompt'

dependency 'puppetlabs/stdlib', '3.2.x'
